# Generated by Django 6.0 on 2026-01-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(choices=[(True, 'Present'), (False, 'Absent')], default=False),
        ),
    ]
